# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c29d31c0c2dcd2f8f0498b9929d2e124f86156ea853b651678080b05a2ec7bb2b76b1350e674e15c62a02186d3a1c6e643c54eaefcecedcbe5ad1832dc5b800

test:
  secret_key_base: 5b7a9c234989e004c8bd9a0d26b893089068a38290c2cdfdf71087416dfc300969542dfe254fac5ab89cc340aeae8b702734563bdc29e9174f8548a839e39b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
